# Generated by Django 5.2.6 on 2025-09-16 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_purchase_pg_purchase_pg_tid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("carrier", models.CharField(max_length=40)),
                ("tracking_number", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out For Delivery"),
                            ("delivered", "Delivered"),
                            ("canceled", "Canceled"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_event_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out For Delivery"),
                            ("delivered", "Delivered"),
                            ("canceled", "Canceled"),
                            ("returned", "Returned"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("last_event_loc", models.CharField(blank=True, max_length=120)),
                ("last_event_desc", models.CharField(blank=True, max_length=200)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="orders.purchase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out For Delivery"),
                            ("delivered", "Delivered"),
                            ("canceled", "Canceled"),
                            ("returned", "Returned"),
                        ],
                        max_length=24,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("provider_code", models.CharField(blank=True, max_length=80)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=20)),
                ("dedupe_key", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipments.shipment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["carrier", "tracking_number"],
                name="shipments_s_carrier_4f3ab4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["user", "created_at"], name="shipments_s_user_id_a5db8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["status", "last_event_at"], name="shipments_s_status_576ef0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.UniqueConstraint(
                fields=("carrier", "tracking_number"), name="uq_carrier_tracking"
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentevent",
            index=models.Index(
                fields=["shipment", "occurred_at"],
                name="shipments_s_shipmen_0b12ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentevent",
            index=models.Index(
                fields=["shipment", "status"], name="shipments_s_shipmen_0c2d4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentevent",
            index=models.Index(
                fields=["dedupe_key"], name="shipments_s_dedupe__a71a08_idx"
            ),
        ),
    ]
