services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shopapi
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"           # host 5433 -> container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shopapi"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      bash -lc "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        exec gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker
          --bind 0.0.0.0:8000
          --workers ${GUNICORN_WORKERS:-4} --threads ${GUNICORN_THREADS:-2}
          --log-level info --access-logfile - --error-logfile -
          --timeout 60 --graceful-timeout 30 --keep-alive 5
          --worker-tmp-dir /dev/shm --forwarded-allow-ips="*"
          --lifespan off
      "
    # 개발 중에만 마운트(운영은 제거 권장)
    volumes:
      - .:/app

volumes:
  dbdata:
