version: "3.9"
services:
  db:
    image: postgres:16
    container_name: shopapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shopapi
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

