# Generated by Django 5.2.6 on 2025-09-27 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True),
        ),
    ]
