# Generated by Django 5.2.6 on 2025-09-16 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super', 'Super'), ('manager', 'Manager'), ('cs', 'CS')], default='manager', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('LOGIN', 'LOGIN')], max_length=20)),
                ('target_table', models.CharField(max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='staff.admin')),
            ],
            options={
                'indexes': [models.Index(fields=['admin'], name='staff_admin_admin_i_8c0295_idx'), models.Index(fields=['action'], name='staff_admin_action_b7f106_idx'), models.Index(fields=['target_table', 'target_id'], name='staff_admin_target__eb9a98_idx'), models.Index(fields=['created_at'], name='staff_admin_created_d9e153_idx')],
            },
        ),
    ]

