# Generated by Django 5.2.6 on 2025-09-18 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_role_super_to_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'admin', 'verbose_name_plural': 'admins'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin'), ('cs', 'CS')], default='manager', max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='staff_admins',
        ),
    ]
