# Generated by Django 5.2.6 on 2025-09-22 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_productstock_option_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('wishlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_key', models.CharField(blank=True, default='', max_length=64)),
                ('options', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist_items',
                'indexes': [models.Index(fields=['user', '-created_at'], name='wishlist_it_user_id_1d7ae2_idx'), models.Index(fields=['product'], name='wishlist_it_product_282ecb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product', 'option_key'), name='uq_wishlist_user_product_option')],
            },
        ),
    ]
