# Generated by Django 5.2.6 on 2025-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['user', 'manager', 'admin', 'cs'])), name='users_role_allowed_values'),
        ),
    ]
