# Generated by Django 5.2.6 on 2025-09-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_socialaccount"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="socialaccount",
            new_name="social_acco_provide_8ea1fc_idx",
            old_name="accounts_so_provide_2b0a13_idx",
        ),
        migrations.AlterModelTable(
            name="socialaccount",
            table="social_accounts",
        ),
    ]
