# Generated by Django 5.2.6 on 2025-09-19 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='option_key',
            field=models.CharField(blank=True, default='', help_text='예: size=L&color=red', max_length=64),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['expires_at'], name='carts_expires_8643c1_idx'),
        ),
    ]
