# Generated by Django 5.2.6 on 2025-09-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_option_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='option_key',
            field=models.CharField(blank=True, default='', help_text='예: size=L&color=BLACK (URL-encoded 권장)', max_length=64),
        ),
    ]
