# Generated by Django 5.2.6 on 2025-09-10 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='paid', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases',
                'indexes': [models.Index(fields=['user'], name='purchases_user_id_1d1d8e_idx'), models.Index(fields=['product'], name='purchases_product_359b79_idx'), models.Index(fields=['status'], name='purchases_status_12ed65_idx'), models.Index(fields=['purchased_at'], name='purchases_purchas_447b9c_idx')],
            },
        ),
    ]
