# Generated by Django 5.2.6 on 2025-09-16 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.UUIDField(db_column='purchase_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('option_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='paid', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('pg', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pg_tid', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases',
                'indexes': [models.Index(fields=['user', 'purchased_at'], name='purchases_user_id_24bd1b_idx'), models.Index(fields=['product', 'purchased_at'], name='purchases_product_2edfd4_idx'), models.Index(fields=['status'], name='purchases_status_12ed65_idx'), models.Index(fields=['option_key'], name='purchases_option__da128d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='ck_purchase_amount_ge_1')],
            },
        ),
    ]
