# Generated by Django 5.2.6 on 2025-09-19 05:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productstock_option_key'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='ck_purchase_amount_ge_1',
        ),
        migrations.AddField(
            model_name='purchase',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='items_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_purchase_amount_ge_0'),
        ),
    ]
