# Generated by Django 5.2.6 on 2025-09-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='pg',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pg_tid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
