# Generated by Django 5.2.6 on 2025-09-19 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productstock_option_key'),
        ('orders', '0002_remove_purchase_ck_purchase_amount_ge_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_id', models.UUIDField(db_column='item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=80)),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('option_key', models.CharField(db_index=True, default='', max_length=64)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchase')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
                ('stock', models.ForeignKey(blank=True, db_column='stock_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productstock')),
            ],
            options={
                'db_table': 'order_items',
                'indexes': [models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'), models.Index(fields=['product'], name='order_items_product_a53db1_idx'), models.Index(fields=['stock'], name='order_items_stock_i_db87b9_idx'), models.Index(fields=['sku'], name='order_items_sku_1b9f90_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='ck_orderitem_qty_ge_1')],
            },
        ),
    ]
