# Generated by Django 5.2.6 on 2025-09-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping_address1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_address2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_memo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_postcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_recipient',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
