# Generated by Django 5.2.6 on 2025-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_purchase_shipping_address1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                    ("merged", "Merged"),
                    ("deleted", "Deleted"),
                ],
                default="paid",
                max_length=20,
            ),
        ),
    ]
