# Generated by Django 5.2.6 on 2025-09-19 02:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('toss', 'Toss')], default='toss', max_length=20)),
                ('provider_payment_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('method', models.CharField(blank=True, choices=[('card', 'Card'), ('virtual_account', 'Virtual Account'), ('account_transfer', 'Account Transfer'), ('mobile_phone', 'Mobile Phone'), ('easy_pay', 'Easy Pay'), ('gift_certificate', 'Gift Certificate')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('waiting_for_deposit', 'Waiting for Deposit'), ('paid', 'Paid'), ('partial_canceled', 'Partial Canceled'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('expired', 'Expired')], default='ready', max_length=32)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_tax_free', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=60, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('receipt_url', models.CharField(blank=True, max_length=255, null=True)),
                ('card_info', models.JSONField(blank=True, null=True)),
                ('virtual_account', models.JSONField(blank=True, null=True)),
                ('easy_pay', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.purchase')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentCancel',
            fields=[
                ('cancel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='requested', max_length=16)),
                ('reason', models.TextField(blank=True, null=True)),
                ('cancel_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_free_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('provider_cancel_key', models.CharField(blank=True, max_length=128, null=True)),
                ('error_code', models.CharField(blank=True, max_length=60, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancels', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_cancels',
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=40)),
                ('provider_status', models.CharField(blank=True, choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('waiting_for_deposit', 'Waiting for Deposit'), ('paid', 'Paid'), ('partial_canceled', 'Partial Canceled'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('expired', 'Expired')], max_length=32, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_events',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'created_at'], name='payments_order_i_6c2ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcancel',
            index=models.Index(fields=['payment', 'created_at'], name='payment_can_payment_6fdb99_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', 'created_at'], name='payment_eve_payment_4bfa6d_idx'),
        ),
    ]
