# Generated by Django 5.2.6 on 2025-09-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='categories_name_98d7d5_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('l1', '대분류'), ('l2', '중분류'), ('l3', '소분류')], db_index=True, default='l1', max_length=2),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='option_key',
            field=models.CharField(db_index=True, help_text='예: size=L&color=red', max_length=64),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'name'], name='categories_level_94b248_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'name'], name='categories_parent__2710fa_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='categories_path_eecba4_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uq_category_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='uq_category_root_name'),
        ),
    ]
