# Generated by Django 5.2.6 on 2025-09-17 08:47

import django.db.models.deletion
import domains.catalog.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_category_categories_name_98d7d5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(db_column='image_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=domains.catalog.models.product_image_upload_to)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('stock', models.ForeignKey(blank=True, db_column='stock_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.productstock')),
            ],
            options={
                'db_table': 'product_images',
                'indexes': [models.Index(fields=['product', 'display_order'], name='product_ima_product_d1c257_idx'), models.Index(fields=['product', 'is_main'], name='product_ima_product_1fb2a2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='ck_product_image_display_order_ge_0')],
            },
        ),
    ]
