# Generated by Django 5.2.6 on 2025-09-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage_is_remote_productimage_remote_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='option_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
